d435i_cloud_filter_chain:
  - name: RobotBodyFilter
    type: robot_body_filter/RobotBodyFilterPointCloud2
    params:
      frames/fixed: D435i_camera_depth_optical_frame
      frames/sensor: D435i_camera_depth_optical_frame
      frames/filtering: D435i_camera_depth_optical_frame
      frames/output: D435i_camera_depth_optical_frame 
      sensor/point_by_point: False
      sensor/min_distance: 0.25
      sensor/max_distance: 1.75
      body_model/inflation/scale: 1.15
      body_model/inflation/padding: 0.075
      body_model/robot_description_param: '/xbotcore/robot_description'
      filter/model_pose_update_interval: 0.0
      filter/keep_clouds_organized: True
      filter/do_clipping: True
      filter/do_contains_test: True
      filter/do_shadow_test: False
      transforms/buffer_length: 15.0
      transforms/timeout/reachable: 0.2
      transforms/timeout/unreachable: 0.2
      transforms/require_all_reachable: False
      bounding_sphere/compute: True
      bounding_box/compute: True
      bounding_sphere/publish_cut_out_pointcloud: True
      bounding_box/publish_cut_out_pointcloud: True 
      ignored_links/bounding_sphere: []
      ignored_links/bounding_box/bounding_sphere: []
      ignored_links/contains_test: []
      ignored_links/shadow_test: []
      ignored_links/everywhere: []
      ignored_links/bounding_box: []
      only_links: []
      body_model/dynamic_robot_description/field_name: robot_model
      local_bounding_box/marker: False
      local_bounding_box/marker: False
      local_bounding_box/frame_id: fixed_frame 
      oriented_bounding_box/compute: False
      oriented_bounding_box/debug: False
      oriented_bounding_box/publish_cut_out_pointcloud: False
      oriented_bounding_box/marker: False
      local_bounding_box/compute: False
      local_bounding_box/publish_cut_out_pointcloud: False
      local_bounding_box/debug: False 
      bounding_sphere/debug: False
      bounding_sphere/marker: False
      bounding_box/debug: False
      bounding_box/marker: False
      debug/pcl/inside: False
      debug/pcl/clip: False
      debug/pcl/shadow: False
      debug/marker/contains: False
      debug/marker/shadow: False
